Exchange buy fix
DecenterApps/defisaver-contracts pull request #23
Opened 2020-09-02 12:35 UTC by yippee-ki-yay

2020-09-03 14:25 UTC, nklipa13 requested changes

2020-09-03 14:25 UTC, nklipa13 commented on contracts/exchange/wrappers/UniswapV2Wrapper.sol
> +        _srcAddr = ethToWethAddr(_srcAddr);
ovo nije potrebno jer uvek to uradimo u exchangeCore

2020-09-03 14:25 UTC, nklipa13 commented on contracts/exchange/wrappers/UniswapV2Wrapper.sol
> +        _srcAddr = ethToWethAddr(_srcAddr);
ovo nije potrebno jer uvek to uradimo u exchangeCore

2020-09-03 16:22 UTC, yippee-ki-yay commented on contracts/mcd/close/MCDCloseFlashLoan.sol
> +        ExchangeData memory _exchangeData,
internal je funkcija zaista nije bitno

2020-09-03 16:23 UTC, yippee-ki-yay commented on test/exchange-prices.js
> +
Jer nisu radili ti testovi a mrzelo me je sve da prepisujem svakako sam testirao sell/buy rateve na svim wrapperima

2020-09-03 16:25 UTC, yippee-ki-yay commented on contracts/exchange/wrappers/UniswapV2Wrapper.sol
> +        _srcAddr = ethToWethAddr(_srcAddr);
getSellRate se ne koristi u exchangeCore

2020-09-03 16:26 UTC, yippee-ki-yay commented on contracts/exchange/wrappers/UniswapV2Wrapper.sol
> +        _srcAddr = ethToWethAddr(_srcAddr);
getBuyRate takodje se ne koristi u exchangeCore

2020-09-04 09:00 UTC, nklipa13 approved these changes
lgtm

2020-09-04 09:00 UTC, merged