Add new FL sources to MCD/Compound
DecenterApps/defisaver-contracts pull request #81
Opened 2021-12-15 11:55 UTC by yippee-ki-yay

Remove old AaveV1 FL and add AaveV2/Balancer with the options for the backend to choose which one the they want to use.
The change was aimed to be minimal and to only add the new FL, the biggest difference is that the old system was getting a FL in ETH but here we get it in WETH.

A few notes:
- Tests are working but are ran from a hard coded block number written in test comments
- Added a separate FLHelper file for common stuff needed between files (view for backend there as well)

2021-12-15 12:44 UTC, majkic99 approved these changes
test works, lgtm, small changes maybe needed

2021-12-15 12:44 UTC, majkic99 commented on contracts/mcd/saver/MCDSaverProxy.sol
> +        bool _toEth
add param to natspec

2021-12-15 12:44 UTC, majkic99 commented on contracts/compound/automatic/CompoundMonitor.sol
> +    address internal compoundSaverFlashLoan;
should one be public one internal?

2021-12-15 12:49 UTC, yippee-ki-yay commented on contracts/compound/automatic/CompoundMonitor.sol
> +    address internal compoundSaverFlashLoan;
I set it internal for deployment gas cost, the old one is public and would keep it that way for easier finding on etherscan when looking which taker addr is called and the second contract can be found in the taker.

2021-12-15 14:08 UTC, kjaredic approved these changes
legitimate

2021-12-16 13:21 UTC, nklipa13 requested changes
Mostly small improvements and one fix in FLHelper needed before merge

2021-12-16 13:21 UTC, nklipa13 commented on contracts/compound/saver/CompoundSaverFlashLoan.sol
> +        require(msg.sender == AAVE_LENDING_POOL, "Only aave pool can call");
Is it better to use:
`ILendingPoolAddressesProviderV2(_market).getLendingPool()` ?

2021-12-16 13:21 UTC, nklipa13 commented on contracts/mcd/saver/MCDSaverFlashLoan.sol
> +        require(msg.sender == AAVE_LENDING_POOL, "Only aave pool can call");
The same question about
`ILendingPoolAddressesProviderV2(_market).getLendingPool()`

2021-12-16 13:21 UTC, nklipa13 commented on contracts/mcd/saver/MCDSaverTaker.sol
> +        _mcdSaverFlashLoanAddr.transfer(msg.value); // 0x fee
We can remove this

2021-12-16 13:21 UTC, nklipa13 commented on contracts/mcd/saver/MCDSaverTaker.sol
> +        _mcdSaverFlashLoanAddr.transfer(msg.value); // 0x fee
We can also remove this

2021-12-16 13:21 UTC, nklipa13 commented on contracts/utils/FLHelper.sol
> +        address MCD_SAVER_FLASH_LOAN
Rename this param

2021-12-16 13:21 UTC, nklipa13 commented on contracts/utils/FLHelper.sol
> +        flLiquidity = getFLLiquidity(FLType.BALANCER, _tokenAddr);
Here it should be FLType.AAVE_V2

2021-12-16 14:22 UTC, nklipa13 approved these changes

2021-12-17 09:15 UTC, merged